_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.10.0
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
                - 77
            "2":
                - 1
                - 5
                - 53
                - 55
                - 77
            "3":
                - 2
                - 23
                - 55
            "4": 3.10.0
            "5": 0.18.7
            "8":
                - 1
                - 2
                - 3
                - 5
            "12": 0.18.7
            "13": windows-amd64
